### ISSUE TITLE
我能问一下Headline Generation是在什么配置下训练了多久吗？

### ISSUE THREAD

**Issue by wang001** [thunlp/SDLM-pytorch#1]
我运行后估算了一下15个epochs在gtx1080ti下要训练一个多星期，请问作者当初训练了多久。

**Comment by junyann** [comment]
您好，实验环境是在单卡GTX 1080 Ti下，所需时间为5-6天。相比原模型所增加的额外时间开销主要在于：(1)hierachical decoder (2)手动实现的稀疏矩阵乘法（PyTorch0.3.1版本不直接支持稀疏矩阵乘法）。
感谢您的关注！

**Comment by wang001** [comment]
谢谢，您能给出处理数据，得到renmin_hownet/*.txt的源码吗？

**Comment by wang001** [comment]
还有，为什么我在网上看到ppl都是2的指数，而这里用的math.exp貌似是e的指数。

**Comment by wmyw96** [comment]
> 谢谢，您能给出处理数据，得到renmin_hownet/*.txt的源码吗？

Here is a sample 

https://drive.google.com/file/d/1wKUgTHbAa55293Qoid8aHZPC_Rijquoi/view?usp=sharing

**Comment by wmyw96** [comment]
> 还有，为什么我在网上看到ppl都是2的指数，而这里用的math.exp貌似是e的指数。

Hi, Thank you for your interests.

The definition of PPL is as follows

   PPL (x_1, x_2, .. x_n) = ( \prod_{i=1}^n { P(x_i | x_{<i}) } ) ^ (-1/n)
                                     = A ^ {(1/n) * \sum_{i=1}^n { -log_A (P(x_i | x_{<i}) ) }

   so A can be any value. In our implementation we use log_e (x) (e.g. Line 203 in `run_awd_lstm.py` ), therefore our implementation is correct (A=e)

**Comment by wmyw96** [comment]
> 谢谢，您能给出处理数据，得到renmin_hownet/*.txt的源码吗？

Here is a sample (use `python hownet_dataset.py` to run)

https://drive.google.com/file/d/1qPQxRGkayX9_ZolH6Jydo1r0Na9jsglL/view?usp=sharing

**Comment by wang001** [comment]
感谢解答和帮助！
