### ISSUE TITLE
请问能把训练好的模型发一下吗？

### ISSUE THREAD

**Issue by wang001** [thunlp/SDLM-pytorch#4]
我略微修改后将代码在pytorch1.0下运行，只运行awd-lstm-bl一次测试集得到ppl=74.34，但是awd-lstm-rnn却从没有到过500以下。

**Comment by wmyw96** [comment]
Here is the link of trained model and training logs:

https://drive.google.com/file/d/1bK6bKAN6p8hP3Koi8uNCWFJzAEDaHQ8i/view?usp=sharing

I thought you may not adapt correctly since our code is implemented and run under pytorch==0.3.1

**Comment by wang001** [comment]
非常感谢，或许是我的改动有BUG吧
