### ISSUE TITLE
论文附录没有找到

### ISSUE THREAD

**Issue by zhajiahe** [thunlp/SDLM-pytorch#7]
你好，论文《Language Modeling with Sparse Product of Sememe Experts》中提到附录(Appendix)中有关于数据预处理和模型参数的详细信息，但是我发现论文中并不存在附录，所以能否提供一下完整的论文地址？

**Comment by wmyw96** [comment]
Hi, the full-text could be found in [arxiv](https://arxiv.org/pdf/1810.12387.pdf)

**Comment by zhajiahe** [comment]
> 
> 
> Hi, the full-text could be found in [arxiv](https://arxiv.org/pdf/1810.12387.pdf)

**Comment by zhajiahe** [comment]
Thanks !
